import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import * as vscode from "vscode";

import {
	applyCopilotPatch,
	findCopilotBundles,
	formatCopilotPatchStatus,
	getCopilotPatchStatus,
	restoreCopilotPatch,
	type CopilotPatchResult,
	type CopilotPatchTarget,
} from "./copilot-patch";
import { collectAppRoots, collectExtensionRoots, isWritable, isWsl } from "./vscode-app-root";
import { PREPARE_USER_VSCODE_COMMAND, registerUserVsCodeCommand } from "./user-vscode-runtime";

const CONFIG_SECTION = "llamacpp";
const AUTO_PATCH_SETTING = "autoPatchCopilot";
const LAST_FAILURE_KEY = "copilotPatch.lastAutoFailure";

function errorText(error: unknown): string {
	return error instanceof Error ? error.message : String(error);
}

function permissionError(message: string): boolean {
	return /eperm|eacces|erofs|access is denied|permission denied/i.test(message);
}

/**
 * Lists the locations a patch search visited, so a "not found" report says what
 * was actually checked instead of only which call failed.
 */
function describeSearch(explicitRoot: string | undefined): string[] {
	const lines: string[] = [`Active application root: ${explicitRoot ?? "unknown"}`];
	const appRoots = collectAppRoots(explicitRoot);
	lines.push(`Application roots checked (${appRoots.length}):`);
	for (const entry of appRoots) {
		lines.push(`  - [${entry.source}] ${entry.root}`);
	}
	const extensionRoots = collectExtensionRoots(explicitRoot);
	lines.push(`Extension directories checked (${extensionRoots.length}):`);
	for (const entry of extensionRoots) {
		lines.push(`  - [${entry.source}] ${entry.root}`);
	}
	return lines;
}

function appendResult(output: vscode.OutputChannel, result: CopilotPatchResult): void {
	output.appendLine(`[${new Date().toISOString()}] ${result.message}`);
	output.appendLine(formatCopilotPatchStatus(result.status));
	output.appendLine("");
}

async function offerReload(message: string, output: vscode.OutputChannel): Promise<void> {
	const choice = await vscode.window.showInformationMessage(message, "Reload Window", "Show Log");
	if (choice === "Reload Window") {
		await vscode.commands.executeCommand("workbench.action.reloadWindow");
	} else if (choice === "Show Log") {
		output.show(true);
	}
}

/**
 * Writes the patch through `pkexec`/`sudo` when the files belong to another
 * user (a system-wide VS Code installation in `/usr/share/code` or
 * `/usr/lib/code`). Only offered after an explicit user action and after a
 * normal write really failed with a permission error.
 */
async function retryWithAdministratorRights(context: vscode.ExtensionContext, output: vscode.OutputChannel): Promise<void> {
	if (process.platform === "win32") {
		void vscode.window.showInformationMessage(
			"Windows does not need this: install VS Code with the User Installer so its files belong to your account."
		);
		return;
	}
	if (isWsl()) {
		void vscode.window.showInformationMessage(
			"A WSL extension host cannot elevate into Windows. Install VS Code with the User Installer on the Windows side " +
				"(its files are writable from /mnt/c), or run a user-owned Linux VS Code."
		);
		return;
	}
	const modulePath = path.join(context.extensionPath, "out", "copilot-patch.js");
	const runnerDir = fs.mkdtempSync(path.join(os.tmpdir(), "llama-vscode-chat-apply-patches-"));
	const runnerPath = path.join(runnerDir, "apply.cjs");
	const nodePath = process.execPath;
	const body = [
		"// Generated by AI Agent Bridge: applies the Copilot Chat patch with administrator rights.",
		"const patch = require(process.argv[2]);",
		"let targets = [];",
		"try { targets = patch.findCopilotBundles(process.argv[3] || undefined); } catch (error) { console.error(String(error)); process.exit(2); }",
		"if (targets.length === 0) { console.error('No Copilot Chat bundle found'); process.exit(2); }",
		"let changed = false;",
		"for (const target of targets) {",
		"  const result = patch.applyCopilotPatch(target, true);",
		"  changed = changed || result.changed;",
		"  console.log(result.message);",
		"  console.log(patch.formatCopilotPatchStatus(result.status));",
		"}",
		"process.exit(changed ? 0 : 3);",
		"",
	].join("\n");
	fs.writeFileSync(runnerPath, body, { encoding: "utf8", flag: "wx", mode: 0o600 });

	const attempts: Array<{ command: string; args: string[] }> = [];
	if (process.platform === "linux") {
				attempts.push({ command: "pkexec", args: ["/usr/bin/env", "ELECTRON_RUN_AS_NODE=1", nodePath, runnerPath, modulePath, vscode.env.appRoot] });
	}
	attempts.push({ command: "sudo", args: ["-n", "/usr/bin/env", "ELECTRON_RUN_AS_NODE=1", nodePath, runnerPath, modulePath, vscode.env.appRoot] });

	for (const attempt of attempts) {
		try {
			const result = execFileSync(attempt.command, attempt.args, { encoding: "utf8", timeout: 120000 });
			output.appendLine(`[${new Date().toISOString()}] Elevated patch via ${attempt.command} succeeded:`);
			output.appendLine(result.trim());
			output.appendLine("");
						fs.rmSync(runnerDir, { recursive: true, force: true });
						void offerReload("Copilot Chat patch applied with administrator rights. Reload the window.", output);
			return;
		} catch (error) {
			output.appendLine(`[${new Date().toISOString()}] Elevated patch via ${attempt.command} failed: ${errorText(error)}`);
		}
	}

	output.appendLine("Elevation was not available (pkexec and passwordless sudo both failed).");
	const quote = (value: string): string => "'" + value.replace(/'/g, "'\"'\"'") + "'";
	output.appendLine("Run this in a terminal to finish the patch: sudo /usr/bin/env ELECTRON_RUN_AS_NODE=1 " +
		[nodePath, runnerPath, modulePath, vscode.env.appRoot].map(quote).join(" "));
	output.appendLine("");
	const choice = await vscode.window.showWarningMessage(
		"Administrator rights are needed to patch this VS Code installation, and automatic elevation was not available.",
		"Show Log"
	);
	if (choice === "Show Log") {
		output.show(true);
	}
}

async function applyTargets(
	output: vscode.OutputChannel,
	targets: CopilotPatchTarget[]
): Promise<{ changed: boolean; permissionFailure: boolean; workbenchSkipped: boolean; results: CopilotPatchResult[] }> {
	const results: CopilotPatchResult[] = [];
	let changed = false;
	let permissionFailure = false;
	let workbenchSkipped = false;
	for (const target of targets) {
		if (process.platform === "linux" && target.appRoot
			&& path.resolve(target.appRoot) !== path.resolve(vscode.env.appRoot) && !isWritable(target.bundlePath)) {
			output.appendLine(`Skipping read-only Copilot in another installation: ${target.bundlePath}`);
			continue;
		}
		try {
			const result = applyCopilotPatch(target, false);
			appendResult(output, result);
			changed = changed || result.changed;
			workbenchSkipped = workbenchSkipped || !result.status.workbenchApplied;
			results.push(result);
		} catch (error) {
			const message = errorText(error);
			output.appendLine(`[${new Date().toISOString()}] Patch failed for ${target.bundlePath}: ${message}`);
			output.appendLine("");
			permissionFailure = permissionFailure || permissionError(message);
			if (targets.length === 1) {
				throw error;
			}
		}
	}
	return { changed, permissionFailure, workbenchSkipped, results };
}

async function applyPatch(
	context: vscode.ExtensionContext,
	output: vscode.OutputChannel,
	userInitiated: boolean
): Promise<void> {
	try {
		const targets = findCopilotBundles(vscode.env.appRoot);
		output.appendLine(`[${new Date().toISOString()}] Copilot Chat bundles found: ${targets.length}`);
		for (const target of targets) {
			output.appendLine(`  - [${target.source ?? "unknown"}] ${target.bundlePath}`);
			output.appendLine(`    workbench: ${target.workbenchPath ?? "not found for this session"}`);
		}
		output.appendLine("");
		if (targets.length === 0) {
			output.appendLine(describeSearch(vscode.env.appRoot).join("\n") + "\n");
			throw new Error(
				"Could not locate Copilot Chat. Install GitHub Copilot Chat for this VS Code, or point VSCODE_APP_ROOT at the application root."
			);
		}

		const { changed, permissionFailure, workbenchSkipped, results } = await applyTargets(output, targets);
		await context.globalState.update(LAST_FAILURE_KEY, undefined);

		if (changed) {
			const withElevation = userInitiated && workbenchSkipped && process.platform !== "win32" && !isWsl();
			const message = workbenchSkipped
				? "AI Agent Bridge patched native model controls. The VS Code workbench part was skipped; reload the window to activate what was applied."
				: "AI Agent Bridge patched native model controls and bounded stored chat tool output. Reload the window to activate them.";
			if (withElevation) {
				const choice = await vscode.window.showInformationMessage(
					message,
					"Reload Window",
					...(process.platform === "linux" && !vscode.env.remoteName ? ["Prepare User VS Code (no root)"] : []),
					"Apply workbench part as administrator",
					"Show Log"
				);
				if (choice === "Reload Window") {
					await vscode.commands.executeCommand("workbench.action.reloadWindow");
				} else if (choice === "Apply workbench part as administrator") {
					retryWithAdministratorRights(context, output);
				} else if (choice === "Prepare User VS Code (no root)") {
					await vscode.commands.executeCommand(PREPARE_USER_VSCODE_COMMAND);
				} else if (choice === "Show Log") {
					output.show(true);
				}
			} else {
				await offerReload(message, output);
			}
			return;
		}
		if (permissionFailure) {
			throw new Error("The Copilot Chat bundle could not be written: permission denied.");
		}
		if (userInitiated) {
			const notices = results.flatMap(result => result.status.notices);
			void vscode.window.showInformationMessage(
				notices.length > 0
					? "Copilot Chat patch is already applied; the VS Code workbench part is not available."
					: "Copilot Chat patches are already active."
			);
		}
	} catch (error) {
		const message = errorText(error);
		output.appendLine(`[${new Date().toISOString()}] Patch failed: ${message}`);
		output.appendLine(describeSearch(vscode.env.appRoot).join("\n") + "\n");
		output.appendLine("");
		if (userInitiated) {
			const buttons = permissionError(message) ? "Retry with administrator rights" : "Show Log";
			const choice = buttons === "Show Log"
				? await vscode.window.showErrorMessage(`Copilot Chat patch failed: ${message}`, "Show Log")
				: await vscode.window.showErrorMessage(`Copilot Chat patch failed: ${message}`,
					...(process.platform === "linux" && !vscode.env.remoteName ? ["Prepare User VS Code (no root)"] : []), buttons, "Show Log");
			if (choice === "Retry with administrator rights") {
				retryWithAdministratorRights(context, output);
			} else if (choice === "Prepare User VS Code (no root)") {
				await vscode.commands.executeCommand(PREPARE_USER_VSCODE_COMMAND);
			} else if (choice === "Show Log") {
				output.show(true);
			}
			return;
		}

		const failureSignature = `${vscode.version}:${message}`;
		if (context.globalState.get<string>(LAST_FAILURE_KEY) === failureSignature) {
			// Permission errors (EPERM, EACCES, EBUSY) are transient — the file
			// may be locked by a concurrent process or Windows Defender, and a
			// subsequent restart often resolves the lock.  Don't suppress the
			// next auto-patch attempt for these.
			const transient = /eperm|eacces|ebusy/i.test(message);
			if (!transient) {
				return;
			}
		}
		await context.globalState.update(LAST_FAILURE_KEY, failureSignature);
		const choice = await vscode.window.showWarningMessage(
			permissionError(message)
				? "AI Agent Bridge cannot write this VS Code installation. Prepare a user-owned copy to apply patches without root."
				: "AI Agent Bridge could not update the Copilot Chat patch for this VS Code build. The original bundle was not modified.",
			...(permissionError(message) && process.platform === "linux" && !vscode.env.remoteName ? ["Prepare User VS Code (no root)"] : []),
			"Show Log",
			"Disable Auto-Patch"
		);
		if (choice === "Prepare User VS Code (no root)") {
			await vscode.commands.executeCommand(PREPARE_USER_VSCODE_COMMAND);
		} else if (choice === "Show Log") {
			output.show(true);
		} else if (choice === "Disable Auto-Patch") {
			await vscode.workspace.getConfiguration(CONFIG_SECTION).update(
				AUTO_PATCH_SETTING,
				false,
				vscode.ConfigurationTarget.Global
			);
		}
	}
}

async function showStatus(output: vscode.OutputChannel): Promise<void> {
	try {
		const targets = findCopilotBundles(vscode.env.appRoot);
		output.appendLine(`[${new Date().toISOString()}] Patch status`);
		if (targets.length === 0) {
			output.appendLine("No Copilot Chat bundle found.");
			output.appendLine(describeSearch(vscode.env.appRoot).join("\n") + "\n");
			output.appendLine("");
			void vscode.window.showWarningMessage("Copilot Chat was not found; see the log for the search list.", "Show Log");
			return;
		}
		const summaries: string[] = [];
		for (const target of targets) {
			const status = getCopilotPatchStatus(target);
			output.appendLine(formatCopilotPatchStatus(status));
			output.appendLine("");
			summaries.push(
				`Copilot Chat ${status.copilotVersion} (${target.source ?? "unknown"}): controls ${
					status.applied ? "applied" : status.legacyPatch ? "legacy" : "not applied"
				}, history bounds ${status.workbenchApplied ? "applied" : "not applied"}`
			);
		}
		const choice = await vscode.window.showInformationMessage(summaries.join("; "), "Show Log");
		if (choice === "Show Log") {
			output.show(true);
		}
	} catch (error) {
		const message = errorText(error);
		output.appendLine(`[${new Date().toISOString()}] Status failed: ${message}`);
		const choice = await vscode.window.showErrorMessage(`Could not inspect Copilot Chat patch: ${message}`, "Show Log");
		if (choice === "Show Log") {
			output.show(true);
		}
	}
}

async function restorePatch(output: vscode.OutputChannel): Promise<void> {
	const confirmation = await vscode.window.showWarningMessage(
		"Restore the original Copilot Chat and VS Code workbench bundles? Native controls and stored tool-output bounds will stop working after reload.",
		{ modal: true },
		"Restore"
	);
	if (confirmation !== "Restore") {
		return;
	}
	try {
		const targets = findCopilotBundles(vscode.env.appRoot);
		if (targets.length === 0) {
			throw new Error("Could not locate Copilot Chat. See the log for the search list.");
		}
		let restored = false;
		for (const target of targets) {
			const status = getCopilotPatchStatus(target);
			if (!status.backupExists) {
				output.appendLine(`[${new Date().toISOString()}] No backup for ${target.bundlePath}; nothing to restore.`);
				continue;
			}
			appendResult(output, restoreCopilotPatch(target));
			restored = true;
		}
		if (restored) {
			await offerReload("Original Copilot Chat bundle restored. Reload the window to activate it.", output);
		} else {
			void vscode.window.showInformationMessage("No Copilot Chat backup was found; nothing to restore.");
		}
	} catch (error) {
		const message = errorText(error);
		output.appendLine(`[${new Date().toISOString()}] Restore failed: ${message}`);
		const choice = await vscode.window.showErrorMessage(`Could not restore Copilot Chat: ${message}`, "Show Log");
		if (choice === "Show Log") {
			output.show(true);
		}
	}
}

export function registerCopilotPatchIntegration(context: vscode.ExtensionContext): void {
	const output = vscode.window.createOutputChannel("AI Agent Bridge Copilot Patch");
	registerUserVsCodeCommand(context, output);
	context.subscriptions.push(
		output,
		vscode.commands.registerCommand("llamacpp.applyCopilotPatch", () => applyPatch(context, output, true)),
		vscode.commands.registerCommand("llamacpp.copilotPatchStatus", () => showStatus(output)),
		vscode.commands.registerCommand("llamacpp.restoreCopilotPatch", () => restorePatch(output))
	);

	if (
		context.extensionMode === vscode.ExtensionMode.Production
		&& vscode.workspace.getConfiguration(CONFIG_SECTION).get<boolean>(AUTO_PATCH_SETTING, true)
	) {
		setTimeout(() => void applyPatch(context, output, false), 0);
	}
}
